# This is a basic workflow that is manually triggered

name: Heroku CLI

on:
  push:
    branches:
      - "master"
env: 
  HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
  HEROKU_PROJECT_PATH: ${{ secrets.HEROKU_PROJECT_PATH }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login to Heroku 
      run: heroku container:login
    - name: Add frontend remote origin
      run: |
        git remote add heroku-api https://heroku:${{ env.HEROKU_AUTH_TOKEN }}@git.heroku.com/${{ env.HEROKU_APP_NAME }}.git
    - name: Build and push in subtree
      run: |
       heroku git:remote -a ${{ env.HEROKU_APP_NAME }}
       git subtree push --prefix ${{ env.HEROKU_PROJECT_PATH }} heroku master
